# Generated by Django 5.0.1 on 2024-01-24 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_consumedcalories_calorie_consumed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumedcalories',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_profile'),
        ),
    ]
