# Generated by Django 5.0.1 on 2024-01-24 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_consumedcalories_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumedcalories',
            name='date_consumed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
