# Generated by Django 5.0.2 on 2024-02-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_consumedcalories_date_consumed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='otp_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
