# Generated by Django 5.0.2 on 2024-02-14 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_user_profile_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='media/profile pic'),
        ),
    ]
